name: Deploy Develop
on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-develop:
    uses: ./.github/workflows/deployment.yaml
    with:
      environment: develop
      domain: https://dev.${{ secrets.APP_DOMAIN }}
  deploy-test:
    uses: ./.github/workflows/deployment.yaml
    with:
      environment: test
      domain: https://test.${{ secrets.APP_DOMAIN }}