name: Deploy Develop
on:
  push:
    branches:
      - uat

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-production:
    uses: ./.github/workflows/deployment.yaml
    secrets: inherit
    with:
      environment: production
      domain: https://${{ secrets.APP_DOMAIN }}
      production: true
