name: Develop deploy

on:
  push:
    branches:
      - develop

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yaml

  deploy-develop:
    needs: [lint-and-test]
    uses: ./.github/workflows/deploy.yaml
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

  sync-with-test:
    needs: [deploy-develop]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: 'test'
          github_token: ${{ secrets.GITHUB_TOKEN }}
