name: Develop deploy

on:
  push:
    branches:
      - develop

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yaml

  deploy-develop:
    needs: [lint-and-test]
    uses: ./.github/workflows/deploy.yaml
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

  sync-with-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: 'develop'
          target_branch: 'test'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
