name: Preview

on:
  pull_request:
    - stage
    - uat
    - master
  workflow_dispatch:

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yaml

  deploy:
    needs: [lint-and-test]
    uses: ./.github/workflows/deploy.yaml
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
