name: UAT deploy or PR to UAT or Prod

on:
  push:
    branches:
      - uat
  pull_request:
    branches:
      - uat
      - master
  workflow_dispatch:

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yaml

  deploy:
    needs: [lint-and-test]
    uses: ./.github/workflows/deploy.yaml
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_TEAM_NAME: ${{ secrets.VERCEL_TEAM_NAME }}
