name: Production manual deploy

on:
  workflow_dispatch:

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yaml

  deploy-master:
    needs: [lint-and-test]
    uses: ./.github/workflows/deploy.yaml
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
