name: Test deploy

on:
  push:
    branches:
      - test
  workflow_run:
    types:
      - completed
    workflows:
      - 'Develop deploy'

jobs:
  deploy-test:
    uses: ./.github/workflows/deploy.yaml
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
