name: Test deploy

on:
  workflow_run:
    workflows: ['Develop deploy']
    types:
      - completed

jobs:
  deploy-test:
    uses: ./.github/workflows/deploy.yaml
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
