name: Test and deploy PROD

on:
  push:
    branches:
      - 'hotfix/**'
      - stage
      - master
  workflow_dispatch:

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yaml

  deploy:
    needs: [lint-and-test]
    uses: ./.github/workflows/deploy.yaml
    with:
      vercel-args: '--prod'
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
