name: Test and deploy PROD
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  # Modify on future envs
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test-and-deploy-prod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.17.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: mskelton/setup-yarn@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Check linting
        run: yarn lint

      - name: Run the tests
        run: yarn test

      - name: Pull Vercel Environment Information
        # Possible envs => development / preview / production
        run: yarn vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: yarn vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: yarn vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
