name: Test deploy

on:
  push:
    branches:
      - test

jobs:
  deploy-test:
    uses: ./.github/workflows/deploy.yaml
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_TEAM_NAME: ${{ secrets.VERCEL_TEAM_NAME }}
